# Generated by Django 3.0.3 on 2020-03-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BRDname', models.CharField(max_length=50, verbose_name='brand name')),
                ('BRDdesc', models.TextField(max_length=200, verbose_name='brand description ')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Varient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VARname', models.CharField(max_length=50, verbose_name='varient name')),
                ('VARdesc', models.TextField(max_length=200, verbose_name='varient description')),
            ],
            options={
                'verbose_name': 'Varient',
                'verbose_name_plural': 'Varients',
            },
        ),
    ]
