# Generated by Django 3.0.3 on 2020-03-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDname', models.CharField(max_length=50, unique=True, verbose_name='product name')),
                ('PRDdesc', models.TextField(max_length=300, verbose_name='product description')),
                ('PRDprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='product price')),
                ('PRDcost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='product cost')),
                ('created_date', models.DateTimeField(verbose_name='created at ')),
            ],
        ),
    ]
