# Generated by Django 3.0.3 on 2020-03-03 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDImg', models.ImageField(upload_to='product/', verbose_name='product image')),
                ('PRDIproductname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astore.Product', verbose_name='product name')),
            ],
        ),
    ]
