# Generated by Django 3.0.3 on 2020-03-03 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astore', '0003_productcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='CATparent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATparent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='astore.ProductCategory', verbose_name='category parent '),
        ),
        migrations.CreateModel(
            name='ProductAlternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDALalternatives', models.ManyToManyField(related_name='alternative_products', to='astore.Product')),
                ('PRDALproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='astore.Product')),
            ],
            options={
                'verbose_name': 'ProductAlternative',
                'verbose_name_plural': 'ProductAlternatives',
            },
        ),
    ]
