# Generated by Django 3.0.3 on 2020-03-03 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astore', '0004_auto_20200303_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAccessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDACCalternatives', models.ManyToManyField(related_name='Accessories_products', to='astore.Product')),
                ('PRDACCproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessory_product', to='astore.Product')),
            ],
            options={
                'verbose_name': 'Product Accessory',
                'verbose_name_plural': 'Product Accessories',
            },
        ),
    ]
