# Generated by Django 3.0.3 on 2020-03-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astore', '0008_product_prdslug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='product',
            name='PRDdiscountprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='discount price'),
            preserve_default=False,
        ),
    ]
