# Generated by Django 3.0.3 on 2020-03-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astore', '0009_auto_20200303_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDIsNew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDIsSeller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDdiscountprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='discount price'),
        ),
    ]
