# Generated by Django 3.0.3 on 2020-03-05 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('astore', '0010_auto_20200303_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='astore.ProductCategory', verbose_name='product category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDIsNew',
            field=models.BooleanField(default=True, verbose_name='product isNew'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDIsSeller',
            field=models.BooleanField(default=False, verbose_name='product isSeller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDbrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Brand', verbose_name='product brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDslug',
            field=models.SlugField(blank=True, null=True, verbose_name='product slug'),
        ),
        migrations.AlterField(
            model_name='productaccessories',
            name='PRDACCalternatives',
            field=models.ManyToManyField(related_name='Accessories_products', to='astore.Product', verbose_name='accessory alternative'),
        ),
        migrations.AlterField(
            model_name='productaccessories',
            name='PRDACCproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessory_product', to='astore.Product', verbose_name='product accessory'),
        ),
        migrations.AlterField(
            model_name='productalternative',
            name='PRDALalternatives',
            field=models.ManyToManyField(related_name='alternative_products', to='astore.Product', verbose_name='alternative product'),
        ),
        migrations.AlterField(
            model_name='productalternative',
            name='PRDALproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='astore.Product', verbose_name='main product'),
        ),
    ]
